Repository cgeo/cgeo, pull requests merged in 2019-08, with the labels that each got.

#7775 optionally assign icon marker to lists
  main/res/layout/cachelist_listmarker_item.xml
  main/res/menu/cache_list_options.xml
  main/res/values/strings.xml
  main/src/cgeo/geocaching/CacheListActivity.java
  main/src/cgeo/geocaching/command/DeleteListCommand.java
  main/src/cgeo/geocaching/list/ListMarker.java
  main/src/cgeo/geocaching/list/StoredList.java
  main/src/cgeo/geocaching/storage/DataStore.java
  main/src/cgeo/geocaching/utils/MapMarkerUtils.java
Labels: Do not merge / WIP

#7777 trackable log list: move gc info to main column to give it more space
  main/res/layout/logs_item.xml
  main/src/cgeo/geocaching/log/LogViewHolder.java
  main/src/cgeo/geocaching/log/TrackableLogsViewCreator.java
Labels: Duplicate, Field test

#7784 update the locus connector
  main/build.gradle
  main/res/values/strings.xml
  main/src/cgeo/geocaching/apps/AbstractLocusApp.java
Labels: Field test

#7778 output warning when restore database failed due to corrupt database
  main/res/values/strings.xml
  main/src/cgeo/geocaching/storage/DataStore.java
  main/src/cgeo/geocaching/utils/DatabaseBackupUtils.java
Labels: Field test

#7791 add visit state toggle button to map's waypoint popup (fix #2592)
  main/res/layout/waypoint_popup.xml
  main/res/values/strings.xml
  main/src/cgeo/geocaching/WaypointPopupFragment.java
Labels: Field test

#7764 add list membership filter
  main/res/values/strings.xml
  main/src/cgeo/geocaching/filter/FilterRegistry.java
  main/src/cgeo/geocaching/filter/ListFilterFactory.java
Labels: Field test

#7785 rename cacheType's
  main/res/values/strings.xml
  main/src/cgeo/geocaching/enumerations/CacheType.java
Labels: Field test

#7768 add cache filters for stored within or before last 8h / 24h / 7d / 30d
  main/res/values/strings.xml
  main/src/cgeo/geocaching/filter/FilterRegistry.java
  main/src/cgeo/geocaching/filter/StateFilterFactory.java
  main/src/cgeo/geocaching/filter/StoredFilterFactory.java
  tests/src-android/cgeo/geocaching/filter/StateStoredFilterTest.java
Labels: Field test

#7769 optionally show additional list memberships in cachelist
  main/res/layout/cacheslist_item.xml
  main/res/menu/cache_list_options.xml
  main/res/values/preference_keys.xml
  main/res/values/strings.xml
  main/src/cgeo/geocaching/CacheListActivity.java
  main/src/cgeo/geocaching/settings/Settings.java
  main/src/cgeo/geocaching/ui/CacheListAdapter.java
Labels: Field test

#7795 add function to batch upload coords for all (selected) caches
  main/res/menu/cache_list_options.xml
  main/res/values/strings.xml
  main/src/cgeo/geocaching/CacheListActivity.java
  main/src/cgeo/geocaching/export/BatchUploadModifiedCoordinates.java
Labels: Field test
