Repository cgeo/cgeo, pull requests merged in 2021-07, with the labels that each got.

#11265 fix #11196: make storedsince range work for non-offline caches
  main/src/cgeo/geocaching/CacheDetailActivity.java
  main/src/cgeo/geocaching/filters/core/StoredSinceGeocacheFilter.java
Labels: Do not merge / WIP

#10987 cleanup components section
  main/res/values/strings_not_translatable.xml
Labels: Feedback required

#11287 ALC no longer working (fix: #11001)
  main/res/values/preference_keys.xml
  main/src/cgeo/geocaching/connector/lc/LCApi.java
  main/src/cgeo/geocaching/settings/Settings.java
  main/templates/keys.xml
  templates/private.properties
Labels: Bug

#11359 get ALC True Found State
  main/src/cgeo/geocaching/connector/lc/LCApi.java
  main/src/cgeo/geocaching/connector/lc/LCConnector.java
Labels: Connector LC
