Repository cgeo/cgeo, pull requests merged in 2025-05, with the labels that each got.

#16910 WIP: Make offline translation preserve HTML
  main/src/main/java/cgeo/geocaching/CacheDetailActivity.java
  main/src/main/java/cgeo/geocaching/utils/OfflineTranslateUtils.java
  main/src/main/res/values/strings.xml
Labels: Do not merge / WIP

#16912 AGP 8.9 / Gradle 8.11
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  main/build.gradle
  settings.gradle
Labels: CI server / Build tools

#16924 Fix #13186: Correct file naming counter during file name creation
  main/src/main/java/cgeo/geocaching/utils/FileNameCreator.java
Labels: safe to test

#16935 Fix #16625: Move upload entries and update labels
  main/src/main/java/cgeo/geocaching/CacheListActivity.java
  main/src/main/res/menu/cache_list_options.xml
  main/src/main/res/values/strings.xml
  main/src/main/res/values/strings_not_translatable.xml
Labels: safe to test

#16920 Use new coordinate entry dialog in all places except waypoint page
  main/src/main/java/cgeo/geocaching/CacheDetailActivity.java
  main/src/main/java/cgeo/geocaching/SearchActivity.java
  main/src/main/java/cgeo/geocaching/filters/gui/DistanceFilterViewHolder.java
  main/src/main/java/cgeo/geocaching/log/LogTrackableActivity.java
  main/src/main/java/cgeo/geocaching/ui/dialog/NewCoordinateInputDialog.java
Labels: safe to test

#16983 #16882: Add snackbar for log visit with share option
  main/src/main/java/cgeo/geocaching/CacheDetailActivity.java
  main/src/main/java/cgeo/geocaching/CacheListActivity.java
  main/src/main/java/cgeo/geocaching/CompassActivity.java
  main/src/main/java/cgeo/geocaching/log/LogCacheActivity.java
  main/src/main/java/cgeo/geocaching/log/LoggingUI.java
  main/src/main/java/cgeo/geocaching/models/Geocache.java
  main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapActivity.java
  main/src/main/java/cgeo/geocaching/utils/ShareUtils.java
  main/src/main/res/values/strings.xml
Labels: ok-to-test
