Repository cgeo/cgeo, pull requests merged in 2025-01, with the labels that each got.

#16474 don't reuse same seekbar in different holders
  main/src/main/java/cgeo/geocaching/settings/SeekbarPreference.java
Labels: Do not merge / WIP

#16515 Update checkstyle
  .idea/checkstyle-idea.xml
  main/build.gradle
Labels: CI server / Build tools

#16486 add parser for DD,DDDDDDD format
  main/src/main/java/cgeo/geocaching/location/GeopointParser.java
  main/src/test/java/cgeo/geocaching/location/GeoPointParserTest.java
Labels: Feedback required

#16524 Show lastUsedFilterName in filter-dialog
  main/src/main/java/cgeo/geocaching/filters/core/GeocacheFilterContext.java
  main/src/main/java/cgeo/geocaching/ui/dialog/SimpleDialog.java
  main/src/main/java/cgeo/geocaching/utils/FilterUtils.java
  main/src/main/res/values/strings.xml
Labels: Feedback required
